---
server:
  port: 8083
  contextPath: /ApplicationService
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:mysql://tweet-db.southcentralus.cloudapp.azure.com:3306/tweetbd
    username: demo
    password: demo
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

